---
#Location of Accounts
AccountsCsv: 'accounts/aws_accounts.csv'

# Query AWS Org for list of Accounts
UseAWSOrganisations: false
MasterAccountRoleArn: 'arn:aws:iam::879492062654:role/tech-auto-master-watchmen-role' # If using AWS Org, provide ARN of role to be used to query AWS Org

# Company's External CIDR Range to lock down Kibana Web Access and S3 Buckets
ExternalCidr: '0.0.0.0/0'

# If using Monitoring, where to send notifications/alerts to:
NotificationEmail: 'name@company.com.au'
NotificationSlack: '#<insert_slack_channel_here>'
SlackChannelHookUrl: 'hooks.slack.com/services/<insert_stuff_here>'

# Test accounts list for canary deployment
CanaryAccounts: {'000000000000', '111111111111'}
